### ISSUE TITLE
Loader/plugin leaking into other entries

### ISSUE THREAD

**Issue by IndianaHorrscht** [vusion/icon-font-loader#15]
I create the icon-font separately from other CSS files, e.g.:

entry: {
"icon-font": [ "icon-font.scss" ],
"main": [ "main.scss", "responsive.scss" ],
"legacy": [ ... ] and so on
...
}

I have a lot of legacy CSS files which need to be compiled separately, so about 80 different entry points. The problem is that the icon font compilation in the plugin (via webfontsGenerator) runs for each of these 80 files, despite 79 of the bundles having nothing to do with icon fonts. This takes a lot of time during the build. Unfortunately I don't know enough about webpack plugins to fix this myself (I have tried). Any lead would be appreciated.

**Comment by rainfore** [comment]
This is not about webpack plugin. This is because the module rule you configured matches all the css files.

Have a try like this:
``` js
module: {
    rules: [
        { test: /^icon-font\.scss$/, use: ['style-loader', 'css-loader', 'icon-font-loader'] },
        { test: /\.css$/, exclude: 'icon-font.scss', use: ['style-loader', 'css-loader'] }
    ],
}
```

**Comment by IndianaHorrscht** [comment]
Thanks for coming back to me. I already have a setup like this. Only the first entry references SVG files/font-icons and only the first entry is being processed through the loader. The other entries are not using font-icons, they are configured seperately via test and without the icon-font-loader as you suggested, but they are processed by the _plugin_ anyway. The callback 'additional-assets' in the plugin gets called for every entry and creates the same icon fonts again and again, once for every entry.

**Comment by rainfore** [comment]
Yeah, I am clear now. It is a problem of our plugin in fact. We will find a way to avoid useless callbacks as soon as possible.

**Comment by rainfore** [comment]
Well, we tried to reproduce this problem but failed.
Can you give us some more details like webpack compiling logs, config file or a simple example better?

**Comment by IndianaHorrscht** [comment]
Here is the example setup:

[icon-font-loader-issue-15-example.tar.gz](https://github.com/vusion/icon-font-loader/files/1506775/icon-font-loader-issue-15-example.tar.gz)

It loads one font-relevant entry, and five others that are unrelated. If you add a console.log in Plugin.js around line 50 (as I did in the node_modules dir that is included) and run the webpack build, you will see the debug output 7 times and thus the icon font being created 7 times. Thanks.

**Comment by rainfore** [comment]
Try this new version [v1.1.1](https://github.com/vusion/icon-font-loader/releases/tag/v1.1.1).
We made some optimization according to your example. It seems that other more compilations are created by `ExtractTextWebpackPlugin` and we avoided generating fonts in those stages.

**Comment by IndianaHorrscht** [comment]
Thanks!
