### ISSUE TITLE
Why font url path change if options.auto

### ISSUE THREAD

**Issue by KenorFR** [vusion/icon-font-loader#21]
Hello,

On line 77 of the Plugin. js file, I see

```
const urlPath = this.options.auto ? this.options.output : '';
let url = path.join(compilation.options.output.publicPath || '', urlPath, urls[type]);
```

The generated CSS file (auto === false) does not take into account the path (options.output) indicated in option. Which, in my case, causes a path error.

I don't see in which case, the omission of the ouput option is justified?

Thank you

**Comment by rainfore** [comment]
Checkout this issue https://github.com/vusion/icon-font-loader/issues/16 and this commit https://github.com/vusion/icon-font-loader/commit/913656fa0092cd35ce6116af75c6f8588c659b2d

**Comment by rainfore** [comment]
Could you give us some more details about your case?
