### ISSUE TITLE
ICON_FONT_LOADER_IMAGE not being replaced with mini-css-extract-plugin is used

### ISSUE THREAD

**Issue by knyy** [vusion/icon-font-loader#26]
Hello good day!

Appreciate help on getting icon-font-loader plugin working with mini-css-extract-plugin. 

ICON_FONT_LOADER_IMAGE is not being replaced. Below is the result via chrome devtools after webpack has built the css (note that the placeholder ICON_FONT_LOADER_IMAGE is still in the css):

> 

.website-header:after {
    font-family: icon-font;
    **content: ICON_FONT_LOADER_IMAGE(1e6cc37447af2dec3798d0a98adb4817);**
}

.website-header:after {
    font-family: 'icon-font';
    font-style: normal;
    font-weight: normal;
    font-variant: normal;
    text-decoration: inherit;
    text-rendering: optimizeLegibility;
    text-transform: none;
    -moz-osx-font-smoothing: grayscale;
    -webkit-font-smoothing: antialiased;
    font-smoothing: antialiased;
    **content: '\F101';**
}
>

### Here is relevant parts of our webpack config:

      {
        test: /\.(scss|css)$/,
        use: [
          process.env.NODE_ENV === "production" ? MiniCssExtractPlugin.loader : {
            loader: require.resolve("style-loader"),
            options: {
              sourceMap: true
            }
          },
          {
            loader: require.resolve("css-loader"),
            options: {
              sourceMap: true,
              importLoaders: 3
            }
          },
          {
            loader: require.resolve("postcss-loader"),
            options: {
              ident: "postcss",
              sourceMap: true,
              plugins: () => postCssPlugins
            }
          },
          {
            loader: require.resolve('icon-font-loader')
          },
          {
            loader: require.resolve("sass-loader"),
            options: {
              sourceMap: true,
              includePaths: [
                path.resolve(`${paths.root}/node_modules`)
              ]
            }
          }
        ]
      }, .....
    plugins: [
      new webpack.DefinePlugin({
        "process.env.NODE_ENV": JSON.stringify(process.env.NODE_ENV)
      }),
      new IconFontPlugin({
        output: './test',
        filename: 'testfilename.[ext]'
      }),
      new MiniCssExtractPlugin({
        filename: "[name].[chunkhash].css",
      }),
      new webpack.HashedModuleIdsPlugin(),
      new CleanWebpackPlugin([paths.output], { verbose: true, root: paths.root }),
      new HtmlWebpackPlugin({
        inject: true,
        template: path.resolve(process.cwd(), paths.mainHTML),
        filename: path.basename(paths.mainHTML),
        chunks: [path.basename(paths.mainHTML, '.html'),
            'runtime'],
        minify: {
          removeComments: true,
          collapseWhitespace: true,
          removeRedundantAttributes: true,
          useShortDoctype: true,
          removeEmptyAttributes: true,
          removeStyleLinkTypeAttributes: true,
          keepClosingSlash: true,
          minifyJS: false, // as prod config uses uglify to do so
          minifyCSS: true,
          minifyURLs: true
        }
     }),
     new InterpolateHtmlPlugin(env.raw),
     new FaviconsWebpackPlugin(paths.favicon),
    new WebpackPwaManifest({
        name: config.name,
        orientation: config.orientation,
        display: config.display,
        start_url: config.start_url,
        short_name: config.short_name,
        description: config.description,
        background_color: config.background_color,
        icons: [{
          src: paths.appIcon || paths.favicon,
          sizes: config.sizes
        }
  ],

**Comment by knyy** [comment]
Thank you for looking into this.
I am using webpack 4 with icon-font-loader 1.5.0

**Comment by knyy** [comment]
Thank you looks like its been fixed, will raise another issue for issues.

**Comment by AlfredMou** [comment]
it has been fixed and close this issue
