### ISSUE TITLE
Incompatibility with babel loader and iconFontStyle module exports being truncated

### ISSUE THREAD

**Issue by knyy** [vusion/icon-font-loader#27]
Hi, thank you for your time, I have encountered two issues detailed below.

**1) Bug when used with webpack 'babel-loader'**

Inside the Plugin.js afterOptimizeTree Hook, allModules.filter function, with babel loader the filepath for comparison to determine if it is iconFontStylePath will fail.

With babel-loader the file path becomes :  D:\projects\my-project\node_modules\babel-loader\lib\index.js??ref--4!D:\projects\my-project\node_modules\icon-font-loader\src\iconFontStyle.js

I am currently patching the issue as below:

    afterOptimizeTree(compilation) {
        const allModules = getAllModules(compilation);
        allModules.filter(function (module) { 
            if(module.request){
                if(path.basename(module.request) === path.basename(this.iconFontStylePath)){
                //module.request vs iconFontStylePath
                //module.request -> D:\projects\my-project\node_modules\babel-loader\lib\index.js??ref--4!D:\projects\my-project\node_modules\icon-font-loader\src\iconFontStyle.js
                //iconFontStylePath - > D:\projects\my-project\node_modules\icon-font-loader\src\iconFontStyle.js
                }
                return path.basename(module.request) === path.basename(this.iconFontStylePath);
            }
            return module.request === this.iconFontStylePath;

        }.bind(this)).forEach((module) => {

**2)** Also, **iconFontStyle module exports being truncated**
``
               source._value = ['module.exports = {',
                    `ICON_FONT_STYLE: ${JSON.stringify(this.styleMessage)}`,
                    '}'].join('\n');
``
Results in the error ../my-project/node_modules/icon-font-loader/src/iconFontStyle.js:1 **Uncaught ReferenceError: s is not defined**
    at eval (../my-project/node_modules/icon-font-loader/src/iconFontStyle.js:1)

If, i add some spaces for the code to become:

``
source._value = ['             module.exports = {',
``

The error goes away and the iconFontStyle.js is rendered correctly.

**Comment by AlfredMou** [comment]
ok, I got it, thank you for your help. it's our bug and we will fix it as soon as possible. Before us fix this bug， you can exclude this loader folder in babel-loader, and this can solve this problem temporarily.

**Comment by rainfore** [comment]
The second problem cannot be reproduced yet.
And we strongly recommand excluding files in `node_modules` for babel-loader. [babel-loader is slow](https://webpack.js.org/loaders/babel-loader/#babel-loader-is-slow-) You can solve it in this way firstly.

**Comment by knyy** [comment]
thanks, have implemented your suggestion in my project, seems working :smile:
