### ISSUE TITLE
The font face declaration is not extracted to the CSS code

### ISSUE THREAD

**Issue by Finesse** [vusion/icon-font-loader#31]
I use the following Webpack configuration to compile **only CSS**:

```js
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const IgnoreEmitPlugin = require('ignore-emit-webpack-plugin');
const IconFontPlugin = require('icon-font-loader').Plugin;

module.exports = {
  entry: {
    main: './src/style.css'
  },
  module: {
    rules: [
      {
        test: /\.css$/,
        use: [
          MiniCssExtractPlugin.loader,
          {
            loader: 'css-loader',
            options: {
              importLoaders: 1
            }
          },
          'icon-font-loader'
        ]
      }
    ]
  },
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: '[name].js'
  },
  plugins: [
    new IconFontPlugin({
      dataURL: true
    }),
    new MiniCssExtractPlugin({
      filename: '[name].css'
    }),
    new IgnoreEmitPlugin(/\.js$/)
  ]
};
```

It takes 1 entry CSS file and emits 1 output CSS file. The [mini-css-extract-plugin](https://github.com/webpack-contrib/mini-css-extract-plugin) is used to extract the CSS code to a CSS file and the [ignore-emit-webpack-plugin](https://github.com/mrbar42/ignore-emit-webpack-plugin) is used to [ignore the main output JS file](https://stackoverflow.com/q/52568420/1118709) that has no content (because the content was extracted to the CSS file).

The output CSS file has a set of rules with `font-family: 'icon-font';`, `font-style: normal;`, etc, but doesn't have the `@font-face` declaration therefore the icons don't work. It happens because the `@font-face` declaration is added to the JS file which is removed. Can you make the plugin inject the `@font-face` rule to the CSS code so that the mini-css-extract-plugin extracts it?

**Comment by AlfredMou** [comment]
Can you accept an additional css file containing @face? If you set auto to false, the plugin will generate a css file for users to introduce into html.
`const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const IgnoreEmitPlugin = require('ignore-emit-webpack-plugin');
const IconFontPlugin = require('icon-font-loader').Plugin;

module.exports = {
  entry: {
    main: './src/style.css'
  },
  module: {
    rules: [
      {
        test: /\.css$/,
        use: [
          MiniCssExtractPlugin.loader,
          {
            loader: 'css-loader',
            options: {
              importLoaders: 1
            }
          },
          'icon-font-loader'
        ]
      }
    ]
  },
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: '[name].js'
  },
  plugins: [
    new IconFontPlugin({
      dataURL: true,
      auto: false,
    }),
    new MiniCssExtractPlugin({
      filename: '[name].css'
    }),
    new IgnoreEmitPlugin(/\.js$/)
  ]
};`

**Comment by Finesse** [comment]
It would be ok (if I don't consider sourcemaps) if I can merge it with my output CSS file and have a single output CSS file. But it sounds like a dirty hack.

**Comment by Finesse** [comment]
FYI there is a very similar plugin [iconfont-webpack-plugin](https://github.com/jantimon/iconfont-webpack-plugin) that adds `@font-face` to the CSS code.

**Comment by rainfore** [comment]
We are going to prepend @font-face CSS to each entry chunk, which means it can be extracted by MiniCSSPlugin.

**Comment by AlfredMou** [comment]
Added to v2.0.0
