### ISSUE TITLE
eot, ttf, woff fonts generated differently every time

### ISSUE THREAD

**Issue by rainfore** [vusion/icon-font-loader#32]
```
        modified:   dist/proto-ui-icon.d05ebfaa73159689.eot
        modified:   dist/proto-ui-icon.d05ebfaa73159689.ttf
        modified:   dist/proto-ui-icon.d05ebfaa73159689.woff
```

**Comment by wt911122** [comment]
svg2ttf introduced timestamp in ttf file unless setting ts directly.
`webfontsGenerator(Object.assign({
            files,
            types,
            fontName,
            writeFiles: false,
            dest: 'build', // Required but not used
            startCodepoint,
        }, fontOptions, {
            formatOptions: {
                // issue #32 eot, ttf, woff fonts generated differently every time
                ttf: {
                    ts: 1451512800000,
                },
            },
        })`

**Comment by rainfore** [comment]
Good job!!
