### ISSUE TITLE
Suggest a vendor-prefix-based property name

### ISSUE THREAD

**Issue by yfwz100** [vusion/icon-font-loader#41]
The current property name `icon-font` is not a standardized in CSS, and It's not in draft either, which causes warnings in editors like VS Code.

![image](https://user-images.githubusercontent.com/983211/105930818-1c800180-6085-11eb-869a-df084e89cf8e.png)

It's better to use a vendor-prefixed name like `-vusion-icon-font` instead of `icon-font`.

E.g. 

```css
.selector {
  -vusion-icon-font: url(./icon.svg);
}

**Comment by rainfore** [comment]
You can use `property` plugin option to custom property name.

``` js
module.exports = {
    entry: {
        bundle: './index.js',
    },
    module: {
        rules: [{ test: /\.css$/, use: ['style-loader', 'css-loader', 'icon-font-loader'] }],
    },
    plugins: [new IconFontPlugin({
        property: '--vusion-icon-font'
    })],
};
```

**Comment by rainfore** [comment]
And thanks! We will consider using vendor-prefixed name as the default value in the next major version.
