### ISSUE TITLE
Webpack 5 compatibility

### ISSUE THREAD

**Issue by KenorFR** [vusion/icon-font-loader#42]
Hello,

I wanted to know if you have planned to adapt the plugin for Webpack 5, apparently you use "extract-text-webpack-plugin" which seems deprecated. 

I've been trying to figure out how to fix this, but despite my attempts, I haven't really had any success except that, apparently, in "BasePlugin.js" of "base-css-image-loader" the "optimizeExtractedChunks" hook doesn't exist anymore because "mini-css-extract-plugin" doesn't implement it.

But I couldn't get the replacement to work in the CSS of url svg (which I guess is done when "optimizeExtractedChunks" is launched)

Thanks for your help.

**Comment by rainfore** [comment]
I'm sorry that we have no plans to adapt this plugin for Webpack 5 in the short term, due to the departure of a core developer.

**Comment by KenorFR** [comment]
I understand, thank you though. I'll try again at greater length if I have to upgrade to webpack 5 via a necessary plugin, for now I finally got by with webpack version 4

**Comment by rainfore** [comment]
With the help of a community contributor, I completed this work. Have a try.
https://github.com/vusion/icon-font-loader/releases/tag/v4.0.0

**Comment by KenorFR** [comment]
Thanks, I'll get back to you as soon as I can (going from webpack 4 to webpack 5, is going to take me some time I think, and this week, I'm following)

**Comment by KenorFR** [comment]
I'm too late, but I wanted to thank you anyway. I've only just switched back to Webpack 5 and version 4 is working perfectly.
